src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraint as Assert;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="integer")
     */
    private $vote;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $share_link;


    /**
     * @ORM\Column(type="integer")
     */
    private $dislikes;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="integer")
     */
    private $shares;

    /**
     * @ORM\Column(type="integer")
     */
    private $replies;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="posts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="LikedPosts")
     */
    private $Likers;

    /**
     * @ORM\ManyToOne(targetEntity=Post::class, inversedBy="comments")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity=Post::class, mappedBy="parent")
     */
    private $comments;



    /**
     * Post constructor.
     */
    public function __construct()
    {
        // Valeurs par défaut de l'entité Post
        $this->setShareLink('/');
        $this->setDislikes(0);
        $this->setReplies(0);
        $this->setShares(0);
        $this->setVote(0);
        $this->setCategory('Uncategorized');
        $this->setUpdatedAt(new \DateTime());
        $this->setCreatedAt(new \DateTime());
        $this->Likers = new ArrayCollection();
        $this->ParentID = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getVote(): ?int
    {
        return $this->vote;
    }

    public function setVote(int $vote): self
    {
        $this->vote = $vote;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getShareLink(): ?string
    {
        return $this->share_link;
    }

    public function setShareLink(string $share_link): self
    {
        $this->share_link = $share_link;

        return $this;
    }

    public function getLikes(): ?int
    {
        return $this->getLikers()->count();
    }


    public function getDislikes(): ?int
    {
        return $this->dislikes;
    }

    public function setDislikes(int $dislikes): self
    {
        $this->dislikes = $dislikes;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getShares(): ?int
    {
        return $this->shares;
    }

    public function setShares(int $shares): self
    {
        $this->shares = $shares;

        return $this;
    }

    public function getReplies(): ?int
    {
        return $this->replies;
    }

    public function setReplies(int $replies): self
    {
        $this->replies = $replies;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getLikers(): Collection
    {
        return $this->Likers;
    }

    public function addLiker(User $liker): self
    {
        if (!$this->Likers->contains($liker)) {
            $this->Likers[] = $liker;
            $liker->likePost($this);
        }

        return $this;
    }

    public function removeLiker(User $liker): self
    {
        if ($this->Likers->contains($liker)) {
            $this->Likers->removeElement($liker);
            $liker->unlikePost($this);
        }

        return $this;
    }

    public function getParent(): ?self
    {
        return $this->parent;
    }

    public function setParent(?self $parent): self
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(self $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setParent($this);
        }

        return $this;
    }

    public function removeComment(self $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getParent() === $this) {
                $comment->setParent(null);
            }
        }

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="date")
     */
    private $anniversary;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $avatar;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $bio;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $slug;

    /**
     * Posts created by this user
     * @ORM\OneToMany(targetEntity=Post::class, mappedBy="author", orphanRemoval=true)
     */
    private $posts;

    /**
     * Posts liked by this user
     * @ORM\ManyToMany(targetEntity=Post::class, inversedBy="Likers")
     */
    private $LikedPosts;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $profile_cover;

    /**
     * User constructor.
     */
    public function __construct()
    {
        $this->setCreatedAt(new \DateTime());
        $this->setAvatar("img/avocat.jpg");
        $this->setProfileCover("img/avocat.jpg");
        $this->posts = new ArrayCollection();
        $this->LikedPosts = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {

        $this->username = $username;

        // Créer un slug dès qu'un utilisateur est définit
        $slugify = new Slugify();
        $slug = $slugify->slugify($username);
        $this->setSlug($slug);

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getAnniversary(): ?\DateTimeInterface
    {
        return $this->anniversary;
    }

    public function setAnniversary(\DateTimeInterface $anniversary): self
    {
        $this->anniversary = $anniversary;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getBio(): ?string
    {
        return $this->bio;
    }

    public function setBio(?string $bio): self
    {
        $this->bio = $bio;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Post[]
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
            $post->setAuthor($this);
        }

        return $this;
    }

    public function removePost(Post $post): self
    {
        if ($this->posts->contains($post)) {
            $this->posts->removeElement($post);
            // set the owning side to null (unless already changed)
            if ($post->getAuthor() === $this) {
                $post->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Post[]
     */
    public function getLikedPosts(): Collection
    {
        return $this->LikedPosts;
    }

    public function likePost(Post $likedPost): self
    {
        if (!$this->LikedPosts->contains($likedPost)) {
            $this->LikedPosts[] = $likedPost;
        }

        return $this;
    }

    public function unlikePost(Post $likedPost): self
    {
        if ($this->LikedPosts->contains($likedPost)) {
            $this->LikedPosts->removeElement($likedPost);
        }

        return $this;
    }

    public function getProfileCover(): ?string
    {
        return $this->profile_cover;
    }

    public function setProfileCover(string $profile_cover): self
    {
        $this->profile_cover = $profile_cover;

        return $this;
    }

    /**
     * @param Post $post
     * @return bool
     */
    public function doesLike(Post $post){
        return $this->LikedPosts->contains($post);
    }
}

templates/includes/category.html.twig
<div class="flex items-center mb-6 border border-solid border-gray-400 category-radius">
    <div class="category-img mr-4">
        <img src="{{ asset("img/catg" ~ id ~ ".jpg") }}" alt="" class="h-full w-full object-cover">
    </div>

    <div>
        <h3 class="inline uppercase text-sm uppercase font-semibold">{{ id ?? "undefined" }} - Category</h3>
        <p class="text-sm text-gray-500">43 posts</p>
    </div>

</div>

templates/includes/friends_suggest.html.twig
<div class="mb-8">

    <div class="flex relative items-center">
        <!-- AVATAR -->
        <button class="overflow-hidden friend-avatar mr-4">
            <img class="object-cover h-full w-full" src="{{ asset('img/avocat.jpg') }}" alt="" />
        </button>

        <div class="flex flex-col">
            <h3 class="font-bold">Blake Scott</h3>
            <p class="text-gray-500 mt">@blake</p>
        </div>

        <button class="h-12 w-12 rounded-full bg-beige text-white ml-auto flex items-center justify-center">
            <img src="{{ asset('img/plus_icon.png') }}" alt="" class="h-5">
        </button>
    </div>


</div>

templates/includes/popular_post.html.twig
<div class="p-8 bg-white card-hover mb-6">

    <a href="#">

        <div class="flex">
            <!-- AVATAR -->
            <button class="w-12 h-12 overflow-hidden rounded-lg mr-4">
                <a href="{{ path('user_profile_by_slug', {slug: upvotedPost.author.slug}) }}">
                    <img class="object-cover h-full" src="{{ asset(upvotedPost.author.avatar) }}" alt=""/>
                </a>
            </button>

            <h3 class="font-bold">
                <a href="{{ path('user_profile_by_slug', {slug: upvotedPost.author.slug}) }}">{{ upvotedPost.author.username }}</a>
            </h3>
        </div>

        <p class="text-gray-600 mt-4">{{ upvotedPost.content }}</p>

        <a href="{{ path('user_profile_by_slug', {slug: upvotedPost.author.slug}) }}" class="text-beige font-bold text-xs float-right mt-2 uppercase">Read</a>
        <span class="float-none invisible h-0">foo</span>

    </a>


</div>

templates/includes/post.html.twig
<article class="p-6 mb-8 card scroll-reveal post" data-post_id="{{ post.id }}">

    <!-- Content -->
    <div class="grid col-post gap-4">

        <!-- COL 1 -->
        <div class="col-post">
            <!-- AVATAR -->
            <button class="w-12 h-12 overflow-hidden rounded-lg">
                <a href="{{ path('user_profile_by_slug', {slug: post.author.slug}) }}"><img class="object-cover h-full" src="{{ post.author.avatar }}" alt=""/></a>
            </button>
        </div>


        <!-- COL 2 -->
        <div class="flex flex-col">

            <!-- Username -->
            <div class="flex items-center mb-2">
                <a href="{{ path('user_profile_by_slug', {slug: post.author.slug}) }}" class="font-semibold">{{ post.author.username }}</a>
                <span class="mx-2 text-xs">-</span>
                <p class="text-xs text-gray-500">Il y a X minutes</p>
            </div>

            <p>{{ post.content }}</p>

            <div class="flex mt-4">
            <button class="py-1 px-4 bg-blue-500 text-white rounded-full text-xs font-semibold mr-2">{{ post.category }}</button>

            </div>
        </div>


        <!-- COL 3 -->
        <div class="whitespace-normal">
            <div class="flex flex-col items-center content-center">

                <!-- arrow up -->
                <button class="p-1 vote-arrow-up">
                    <svg class="h-3"viewBox="0 0 76 96" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                        <g id="Page-1" stroke="none" stroke-width="1"fill-rule="evenodd">
                            <g id="noun_up_1920769" transform="translate(-12.000000, 0.000000)" fill="#000" fill-rule="nonzero">
                                <path d="M57.4,92.4 L84.2,65.6 C88.3,61.5 88.3,54.8 84.2,50.7 C80.1,46.6 73.4,46.6 69.3,50.7 L60.5,59.5 L60.5,11 C60.5,5.2 55.8,0.5 50,0.5 C44.2,0.5 39.5,5.2 39.5,11 L39.5,59.6 L30.6,50.7 C26.5,46.6 19.8,46.6 15.7,50.7 C13.6,52.8 12.6,55.4 12.6,58.1 C12.6,60.8 13.6,63.5 15.7,65.5 L42.5,92.3 C44.5,94.3 47.1,95.4 49.9,95.4 C52.8,95.5 55.5,94.4 57.4,92.4 Z" id="Path" transform="translate(49.937500, 47.953136) rotate(-180.000000) translate(-49.937500, -47.953136) "></path>
                            </g>
                        </g>
                    </svg>
                </button>


                <!-- Upvotes -->
                <p class="text-sm my-1" style="word-break: break-all;">{{ post.vote }}</p>


                <!-- arrow down -->
                <a href="" class="p-1 vote-arrow-down">
                    <svg class="h-3" viewBox="0 0 76 96" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                        <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <g id="noun_down_1920769" transform="translate(-12.000000, 0.000000)" fill="#000" fill-rule="nonzero">
                                <path d="M57.4,92.4 L84.2,65.6 C88.3,61.5 88.3,54.8 84.2,50.7 C80.1,46.6 73.4,46.6 69.3,50.7 L60.5,59.5 L60.5,11 C60.5,5.2 55.8,0.5 50,0.5 C44.2,0.5 39.5,5.2 39.5,11 L39.5,59.6 L30.6,50.7 C26.5,46.6 19.8,46.6 15.7,50.7 C13.6,52.8 12.6,55.4 12.6,58.1 C12.6,60.8 13.6,63.5 15.7,65.5 L42.5,92.3 C44.5,94.3 47.1,95.4 49.9,95.4 C52.8,95.5 55.5,94.4 57.4,92.4 Z" id="Path"></path>
                            </g>
                        </g>
                    </svg>
                </a>
            </div>
        </div>
    </div>

    {{ include('includes/post_reply_1.html.twig') }}

    {% if post.parentId is not empty %}

        {{ include('includes/post_reply_1.html.twig')}}

    {% endif %}

   {{ include('includes/post_reply_2.html.twig')}}

   {{ include('includes/post_reply_1.html.twig')}}

   {{ include('includes/post_reply_1.html.twig')}}

   {{ include('includes/post_reply_2.html.twig')}}






    {#<div class="flex justify-center">
        <a href="" class="text-beige mt-4">Voir plus de réponses</a>
    </div>#}


    <!-- Socials -->
    <div class="flex items-center justify-between mt-6 px-6">
        <div class="flex items-center">

            <!-- Share icon -->
                <a href="" class=" mr-6 p-1">
                    <img src="{{ asset('img/share_icon.svg') }}" alt="" class="w-3 h-3">
                </a>

            <!-- Reply icon -->
            <img src="{{ asset('img/reply_icon.svg') }}" alt="" class="w-4 h-4 mr-1">
            <span class="text-xs font-semibold mr-6">{{ post.replies }}</span>

            <!-- Retweet icon -->
            <img src="{{ asset('img/retweet_icon.svg') }}" alt="" class="w-4 h-4 mr-1">
            <span class="text-xs font-semibold">{{ post.shares }}</span>
        </div>
        
        <div class="flex items-center">

            <!-- Hearth icon -->
            <span class="text-xs font-semibold mr-1 {{ app.user.doesLike(post) ? 'text-green-active' : '' }}">
                {{ post.likes }}
            </span>

            <a href="{{ path('app_like_post', {id: post.id}) }}" class="mr-3 p-1 app-like-btn">
                <img src="{{ asset('img/hearth_icon.svg') }}" alt="" class="w-4 h-4">
            </a>

            <!-- Hearthbreak icon -->
            <span class="text-xs font-semibold mr-1">
                {{ post.dislikes }}
            </span>
            <a href="" class="p-1 app-dislike-btn">
                <img src="{{ asset('img/hearthbreak_icon.svg') }}" alt="" class="w-4 h-4 ">
            </a>
        </div>
    </div>




</article>

templates/includes/post_reply_1.html.twig
<!-- Answers lvl 1 -->
<div class="border border-solid border-gray-300 category-radius p-6 mt-6">

    <div class="grid col-reply gap-4">

        <!-- COL 1 -->
        <div class="col-post">
            <!-- AVATAR -->
            <button class="w-12 h-12 overflow-hidden rounded-lg">
                <img class="object-cover h-full" src="{{ post.author.avatar }}" alt="" />
            </button>
        </div>


        <!-- COL 2 -->
        <div class="flex flex-col">

            <!-- Username -->
            <p class="font-semibold mb-2">{{ post.author.username }}</p>

            <p>{{ post.content }}</p>

        </div>


    </div>

    {{ include('includes/reply_socials.html.twig') }}

</div>

templates/includes/post_socials.html.twig
<!-- Socials -->
<div class="flex items-center justify-between mt-6 px-6">
    <div class="flex items-center">

        <!-- Share icon -->
        <a href="" class=" mr-6 p-1">
            <img src="{{ asset('img/share_icon.svg') }}" alt="" class="w-3 h-3">
        </a>

        <!-- Reply icon -->
        <img src="{{ asset('img/reply_icon.svg') }}" alt="" class="w-4 h-4 mr-1">
        <span class="text-xs font-semibold mr-6">{{ post.replies }}</span>

        <!-- Retweet icon -->
        <img src="{{ asset('img/retweet_icon.svg') }}" alt="" class="w-4 h-4 mr-1">
        <span class="text-xs font-semibold">{{ post.shares }}</span>
    </div>

    <div class="flex items-center">

        <!-- Hearth icon -->
        <span class="text-xs font-semibold mr-1 {{ app.user.doesLike(post) ? 'text-green-active' : '' }}">
                {{ post.likes }}
            </span>

        <a href="{{ path('app_like_post', {id: post.id}) }}" class="mr-3 p-1 app-like-btn">
            <img src="{{ asset('img/hearth_icon.svg') }}" alt="" class="w-4 h-4">
        </a>

        <!-- Hearthbreak icon -->
        <span class="text-xs font-semibold mr-1">
                {{ post.dislikes }}
            </span>
        <a href="" class="p-1 app-dislike-btn">
            <img src="{{ asset('img/hearthbreak_icon.svg') }}" alt="" class="w-4 h-4 ">
        </a>
    </div>
</div>

templates/includes/reply_socials.html.twig
<!-- Socials -->
<div class="flex items-center justify-between mt-6 px-6">
    <div class="flex items-center">


        <!-- Reply icon -->
        <img src="{{ asset('img/reply_icon.svg') }}" alt="" class="w-4 h-4 mr-1">
        <span class="text-xs font-semibold mr-1">{{ post.replies }}</span>
        <p class="text-xs">réponses</p>

    </div>

    <div class="flex items-center">

        <!-- Hearth icon -->
        <span class="text-xs font-semibold mr-1 {{ app.user.doesLike(post) ? 'text-green-active' : '' }}">
                {{ post.likes }}
            </span>

        <a href="{{ path('app_like_post', {id: post.id}) }}" class="mr-3 p-1 app-like-btn">
            <img src="{{ asset('img/hearth_icon.svg') }}" alt="" class="w-4 h-4">
        </a>

        <!-- Hearthbreak icon -->
        <span class="text-xs font-semibold mr-1">
                {{ post.dislikes }}
            </span>
        <a href="" class="p-1 app-dislike-btn">
            <img src="{{ asset('img/hearthbreak_icon.svg') }}" alt="" class="w-4 h-4 ">
        </a>
    </div>

</div>

templates/includes/user_profile_infos.html.twig
<div class="mx-auto w-full px-8">

    <!-- Card Profile -->
    <div class="p-6 mb-8 card overflow-hidden relative">

        <!-- BANNER -->
        <div class="w-full h-64 overflow-hidden mb-8 absolute top-0 left-0">

            <a href="" class="">
                <div class="flex items-center absolute top-0 right-0 h-4 mr-5 mt-5">
                    <p class="text-white mr-2 text-sm">Editer</p>
                    <svg fill="#ffffff" height="h-3" viewBox="0 0 79 79" version="1.1"
                         xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                        <title>Group</title>
                        <g id="Page-1" stroke="none" stroke-width="1" fill-rule="evenodd">
                            <g id="noun_edit_1268878" transform="translate(-11.000000, 0.000000)" fill-rule="nonzero">
                                <g id="Group" transform="translate(11.110000, 0.122640)">
                                    <path d="M76.89,8.49736013 L69.28,0.877360134 C68.1087298,-0.292453378 66.2112702,-0.292453378 65.04,0.877360134 L36.66,29.2373601 C36.3560936,29.5405513 36.1207954,29.9054339 35.97,30.3073601 L31.39,42.5073601 C30.978915,43.6080744 31.2482455,44.8474511 32.0790773,45.6782828 C32.9099091,46.5091146 34.1492857,46.7784451 35.25,46.3673601 L47.45,41.7973601 C47.8519262,41.6465647 48.2168089,41.4112665 48.52,41.1073601 L76.89,12.7373601 C78.0598135,11.5660899 78.0598135,9.66863032 76.89,8.49736013 Z M44.75,36.3973601 L39.34,38.3973601 L41.34,32.9873601 L67.15,7.22736013 L70.53,10.6073601 L44.75,36.3973601 Z"
                                          id="Shape"></path>
                                    <path d="M69.8,68.7673601 L69.8,42.8773601 C69.8,41.2205059 68.4568542,39.8773601 66.8,39.8773601 C65.1431458,39.8773601 63.8,41.2205059 63.8,42.8773601 L63.8,68.7773601 C63.8,70.4342144 62.4568542,71.7773601 60.8,71.7773601 L9,71.7773601 C7.34314575,71.7773601 6,70.4342144 6,68.7773601 L6,16.9673601 C6,15.3105059 7.34314575,13.9673601 9,13.9673601 L34.89,13.9673601 C36.5468542,13.9673601 37.89,12.6242144 37.89,10.9673601 C37.89,9.31050588 36.5468542,7.96736013 34.89,7.96736013 L9,7.96736013 C4.02943725,7.96736013 0,11.9967974 0,16.9673601 L0,68.7673601 C0,73.7379229 4.02943725,77.7673601 9,77.7673601 L60.8,77.7673601 C65.7705627,77.7673601 69.8,73.7379229 69.8,68.7673601 L69.8,68.7673601 Z"
                                          id="Path"></path>
                                </g>
                            </g>
                        </g>
                    </svg>
                </div>
            </a>

            <div class="flex items-center absolute bottom-0 right-0 mb-3 mr-3">
                <!-- ADD FRIEND -->
                <button class="h-8 p-4 flex items-center rounded-lg bg-white mr-2">
                    <img src="{{ asset('img/add_user_icon.svg') }}" alt="" class="h-4 mr-2">
                    <p class="mr-2">Add friend</p>
                </button>

                <!-- REMOVE FRIEND -->
                <button class="h-8 p-4 flex items-center rounded-lg bg-beige text-white">
                    <p>Remove friend</p>
                </button>
            </div>

            <img src="{{ asset(user.profileCover) }}" alt="" class="w-full object-cover">
        </div>

        <!-- Content -->
        <div class="flex relative mt-64">

            <div>
                <!-- AVATAR -->
                <button class="friend-avatar overflow-hidden rounded-lg">
                    <img class="object-cover h-full" src="{{ user.avatar }}" alt="" />
                </button>
            </div>

            <div class="ml-4">
                <!-- Username -->
                <div class="flex items-center">
                    <a href="" class="font-semibold text-xl">{{ user.username }}</a>
                    <span class="mx-2 text-xs">-</span>
                    <p class="text-xs text-gray-500">{{ user.city }}</p>
                </div>

                <p class="text-xs text-gray-500 mb-3">{{ user.anniversary | date("d/m/Y") }}</p>

                <div class="flex items-center mb-3">
                    <a href="" class="text-xs text-beige">(0) Abonnements</a>
                    <span class="mx-2 text-gray-500">|</span>
                    <a href="" class="text-xs text-beige">(0) Abonnés</a>
                </div>

                <p>{{ user.bio }}</p>

            </div>

        </div>

    </div>
    <!-- End Card Profile -->

    {% for post in posts %}
        {% include "includes/post.html.twig" %}
    {% endfor %}

</div>